const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Behaviors.Sin,
		C3.Plugins.video,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pin,
		C3.Behaviors.Rotate,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.solid,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Text: 0},
	{Sprite4: 0},
	{Text2: 0},
	{Touch: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Text3: 0},
	{Text4: 0},
	{Sine: 0},
	{Text5: 0},
	{Text6: 0},
	{Video: 0},
	{DragDrop: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Text7: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{hp: 0},
	{Pin: 0},
	{Rotate: 0},
	{Physics: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Text8: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{Platform: 0},
	{Sprite16: 0},
	{Solid: 0},
	{Sprite17: 0},
	{Video2: 0},
	{Video3: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	Text6: class extends self.ITextInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Text7: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Text8: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Video3: class extends self.IWorldInstance {}
}